<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CenterSeeder extends Seeder
{
    public function run()
    {
        DB::table('centers')->insert([
            [
            "user_id" => 1,
            "name" => "Chilenje South Clinic",
            "email" => "",
            "phone" => "0977001001",
            "type" => "clinic",
            "lat" => -15.46451,
            "lng" => 28.242822,
            "status" => "active",
            "address" => "Chilenje South Clinic, Lusaka, Zambia",
            "description" => "Chilenje South Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Matero First Level Hospital",
            "email" => "",
            "phone" => "0977001002",
            "type" => "hospital",
            "lat" => -15.416579,
            "lng" => 28.255987,
            "status" => "active",
            "address" => "Matero First Level Hospital, Lusaka, Zambia",
            "description" => "Matero First Level Hospital provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Kalingalinga Health Centre",
            "email" => "",
            "phone" => "0977001003",
            "type" => "center",
            "lat" => -15.462681,
            "lng" => 28.292247,
            "status" => "active",
            "address" => "Kalingalinga Health Centre, Lusaka, Zambia",
            "description" => "Kalingalinga Health Centre provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Chelstone Clinic",
            "email" => "",
            "phone" => "0977001004",
            "type" => "clinic",
            "lat" => -15.375843,
            "lng" => 28.331454,
            "status" => "active",
            "address" => "Chelstone Clinic, Lusaka, Zambia",
            "description" => "Chelstone Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Bauleni Health Post",
            "email" => "",
            "phone" => "0977001005",
            "type" => "health post",
            "lat" => -15.415737,
            "lng" => 28.327544,
            "status" => "active",
            "address" => "Bauleni Health Post, Lusaka, Zambia",
            "description" => "Bauleni Health Post provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Mtendere Health Centre",
            "email" => "",
            "phone" => "0977001006",
            "type" => "center",
            "lat" => -15.386691,
            "lng" => 28.272239,
            "status" => "active",
            "address" => "Mtendere Health Centre, Lusaka, Zambia",
            "description" => "Mtendere Health Centre provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Libala Clinic",
            "email" => "",
            "phone" => "0977001007",
            "type" => "clinic",
            "lat" => -15.393317,
            "lng" => 28.283528,
            "status" => "active",
            "address" => "Libala Clinic, Lusaka, Zambia",
            "description" => "Libala Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Chipata Level One Hospital",
            "email" => "",
            "phone" => "0977001008",
            "type" => "hospital",
            "lat" => -15.371232,
            "lng" => 28.316528,
            "status" => "active",
            "address" => "Chipata Level One Hospital, Lusaka, Zambia",
            "description" => "Chipata Level One Hospital provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Chaisa Clinic",
            "email" => "",
            "phone" => "0977001009",
            "type" => "clinic",
            "lat" => -15.431647,
            "lng" => 28.305614,
            "status" => "active",
            "address" => "Chaisa Clinic, Lusaka, Zambia",
            "description" => "Chaisa Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Kanyama First Level Hospital",
            "email" => "",
            "phone" => "0977001010",
            "type" => "hospital",
            "lat" => -15.407347,
            "lng" => 28.311353,
            "status" => "active",
            "address" => "Kanyama First Level Hospital, Lusaka, Zambia",
            "description" => "Kanyama First Level Hospital provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "George Clinic",
            "email" => "",
            "phone" => "0977001011",
            "type" => "clinic",
            "lat" => -15.458906,
            "lng" => 28.266539,
            "status" => "active",
            "address" => "George Clinic, Lusaka, Zambia",
            "description" => "George Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Garden Clinic",
            "email" => "",
            "phone" => "0977001012",
            "type" => "clinic",
            "lat" => -15.40997,
            "lng" => 28.274114,
            "status" => "active",
            "address" => "Garden Clinic, Lusaka, Zambia",
            "description" => "Garden Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Ngombe Health Centre",
            "email" => "",
            "phone" => "0977001013",
            "type" => "center",
            "lat" => -15.36852,
            "lng" => 28.285832,
            "status" => "active",
            "address" => "Ngombe Health Centre, Lusaka, Zambia",
            "description" => "Ngombe Health Centre provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "PHI Clinic",
            "email" => "",
            "phone" => "0977001014",
            "type" => "clinic",
            "lat" => -15.44089,
            "lng" => 28.248585,
            "status" => "active",
            "address" => "PHI Clinic, Lusaka, Zambia",
            "description" => "PHI Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Chawama Clinic",
            "email" => "",
            "phone" => "0977001015",
            "type" => "clinic",
            "lat" => -15.450332,
            "lng" => 28.257669,
            "status" => "active",
            "address" => "Chawama Clinic, Lusaka, Zambia",
            "description" => "Chawama Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Jack Compound Clinic",
            "email" => "",
            "phone" => "0977001016",
            "type" => "clinic",
            "lat" => -15.387409,
            "lng" => 28.241493,
            "status" => "active",
            "address" => "Jack Compound Clinic, Lusaka, Zambia",
            "description" => "Jack Compound Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Woodlands Health Post",
            "email" => "",
            "phone" => "0977001017",
            "type" => "health post",
            "lat" => -15.447925,
            "lng" => 28.260781,
            "status" => "active",
            "address" => "Woodlands Health Post, Lusaka, Zambia",
            "description" => "Woodlands Health Post provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Kabwata Clinic",
            "email" => "",
            "phone" => "0977001018",
            "type" => "clinic",
            "lat" => -15.367176,
            "lng" => 28.254038,
            "status" => "active",
            "address" => "Kabwata Clinic, Lusaka, Zambia",
            "description" => "Kabwata Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Linda Clinic",
            "email" => "",
            "phone" => "0977001019",
            "type" => "clinic",
            "lat" => -15.407662,
            "lng" => 28.319736,
            "status" => "active",
            "address" => "Linda Clinic, Lusaka, Zambia",
            "description" => "Linda Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Olympia Park Clinic",
            "email" => "",
            "phone" => "0977001020",
            "type" => "clinic",
            "lat" => -15.450922,
            "lng" => 28.297117,
            "status" => "active",
            "address" => "Olympia Park Clinic, Lusaka, Zambia",
            "description" => "Olympia Park Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Northmead Health Centre",
            "email" => "",
            "phone" => "0977001021",
            "type" => "center",
            "lat" => -15.385505,
            "lng" => 28.258621,
            "status" => "active",
            "address" => "Northmead Health Centre, Lusaka, Zambia",
            "description" => "Northmead Health Centre provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Kamwala South Clinic",
            "email" => "",
            "phone" => "0977001022",
            "type" => "clinic",
            "lat" => -15.424273,
            "lng" => 28.25345,
            "status" => "active",
            "address" => "Kamwala South Clinic, Lusaka, Zambia",
            "description" => "Kamwala South Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Zani Muone Clinic",
            "email" => "",
            "phone" => "0977001023",
            "type" => "clinic",
            "lat" => -15.387084,
            "lng" => 28.249544,
            "status" => "active",
            "address" => "Zani Muone Clinic, Lusaka, Zambia",
            "description" => "Zani Muone Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Foxdale Clinic",
            "email" => "",
            "phone" => "0977001024",
            "type" => "clinic",
            "lat" => -15.399793,
            "lng" => 28.281081,
            "status" => "active",
            "address" => "Foxdale Clinic, Lusaka, Zambia",
            "description" => "Foxdale Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Roma Health Post",
            "email" => "",
            "phone" => "0977001025",
            "type" => "health post",
            "lat" => -15.402255,
            "lng" => 28.309664,
            "status" => "active",
            "address" => "Roma Health Post, Lusaka, Zambia",
            "description" => "Roma Health Post provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Twin Palm Clinic",
            "email" => "",
            "phone" => "0977001026",
            "type" => "clinic",
            "lat" => -15.401216,
            "lng" => 28.267797,
            "status" => "active",
            "address" => "Twin Palm Clinic, Lusaka, Zambia",
            "description" => "Twin Palm Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Salama Park Clinic",
            "email" => "",
            "phone" => "0977001027",
            "type" => "clinic",
            "lat" => -15.409199,
            "lng" => 28.242064,
            "status" => "active",
            "address" => "Salama Park Clinic, Lusaka, Zambia",
            "description" => "Salama Park Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "New Kasama Health Centre",
            "email" => "",
            "phone" => "0977001028",
            "type" => "center",
            "lat" => -15.458666,
            "lng" => 28.315561,
            "status" => "active",
            "address" => "New Kasama Health Centre, Lusaka, Zambia",
            "description" => "New Kasama Health Centre provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Makeni Health Centre",
            "email" => "",
            "phone" => "0977001029",
            "type" => "center",
            "lat" => -15.409439,
            "lng" => 28.270393,
            "status" => "active",
            "address" => "Makeni Health Centre, Lusaka, Zambia",
            "description" => "Makeni Health Centre provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Mandevu Clinic",
            "email" => "",
            "phone" => "0977001030",
            "type" => "clinic",
            "lat" => -15.394169,
            "lng" => 28.330168,
            "status" => "active",
            "address" => "Mandevu Clinic, Lusaka, Zambia",
            "description" => "Mandevu Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Misisi Clinic",
            "email" => "",
            "phone" => "0977001031",
            "type" => "clinic",
            "lat" => -15.43261,
            "lng" => 28.267006,
            "status" => "active",
            "address" => "Misisi Clinic, Lusaka, Zambia",
            "description" => "Misisi Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "John Laing Clinic",
            "email" => "",
            "phone" => "0977001032",
            "type" => "clinic",
            "lat" => -15.436667,
            "lng" => 28.28591,
            "status" => "active",
            "address" => "John Laing Clinic, Lusaka, Zambia",
            "description" => "John Laing Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Matero East Clinic",
            "email" => "",
            "phone" => "0977001033",
            "type" => "clinic",
            "lat" => -15.415801,
            "lng" => 28.295982,
            "status" => "active",
            "address" => "Matero East Clinic, Lusaka, Zambia",
            "description" => "Matero East Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Ibex Hill Health Post",
            "email" => "",
            "phone" => "0977001034",
            "type" => "health post",
            "lat" => -15.432738,
            "lng" => 28.317409,
            "status" => "active",
            "address" => "Ibex Hill Health Post, Lusaka, Zambia",
            "description" => "Ibex Hill Health Post provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
            [
            "user_id" => 1,
            "name" => "Mtendere East Clinic",
            "email" => "",
            "phone" => "0977001035",
            "type" => "clinic",
            "lat" => -15.386429,
            "lng" => 28.283896,
            "status" => "active",
            "address" => "Mtendere East Clinic, Lusaka, Zambia",
            "description" => "Mtendere East Clinic provides essential healthcare services to the community.",
            "is_verified" => true,
            ],
        ]);
    }
}
