<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IncidentSeeder extends Seeder
{
    public function run()
    {
        DB::table('incidents')->insert([
            [
            "user_id" => 1,
            "name" => "Theft in Chelstone",
            "type" => "Theft",
            "area" => "Chelstone",
            "details" => "A theft was reported in Chelstone. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.452424,
            "lng" => 28.316039,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Chilenje",
            "type" => "Disease Outbreak",
            "area" => "Chilenje",
            "details" => "A disease outbreak was reported in Chilenje. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.434393,
            "lng" => 28.308563,
            ],
            [
            "user_id" => 1,
            "name" => "Theft in Garden",
            "type" => "Theft",
            "area" => "Garden",
            "details" => "A theft was reported in Garden. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.399497,
            "lng" => 28.30295,
            ],
            [
            "user_id" => 1,
            "name" => "Flood in Kanyama",
            "type" => "Flood",
            "area" => "Kanyama",
            "details" => "A flood was reported in Kanyama. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.401162,
            "lng" => 28.325104,
            ],
            [
            "user_id" => 1,
            "name" => "Accident in Mtendere",
            "type" => "Accident",
            "area" => "Mtendere",
            "details" => "A accident was reported in Mtendere. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.446775,
            "lng" => 28.282824,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Bauleni",
            "type" => "Disease Outbreak",
            "area" => "Bauleni",
            "details" => "A disease outbreak was reported in Bauleni. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.447915,
            "lng" => 28.252301,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Bauleni",
            "type" => "Disease Outbreak",
            "area" => "Bauleni",
            "details" => "A disease outbreak was reported in Bauleni. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.41536,
            "lng" => 28.245737,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Ngombe",
            "type" => "Disease Outbreak",
            "area" => "Ngombe",
            "details" => "A disease outbreak was reported in Ngombe. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.40743,
            "lng" => 28.319153,
            ],
            [
            "user_id" => 1,
            "name" => "Flood in Bauleni",
            "type" => "Flood",
            "area" => "Bauleni",
            "details" => "A flood was reported in Bauleni. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.40396,
            "lng" => 28.265582,
            ],
            [
            "user_id" => 1,
            "name" => "Theft in Ngombe",
            "type" => "Theft",
            "area" => "Ngombe",
            "details" => "A theft was reported in Ngombe. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.462805,
            "lng" => 28.292527,
            ],
            [
            "user_id" => 1,
            "name" => "Fire in Mtendere",
            "type" => "Fire",
            "area" => "Mtendere",
            "details" => "A fire was reported in Mtendere. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.411344,
            "lng" => 28.285027,
            ],
            [
            "user_id" => 1,
            "name" => "Accident in Chawama",
            "type" => "Accident",
            "area" => "Chawama",
            "details" => "A accident was reported in Chawama. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.405895,
            "lng" => 28.304645,
            ],
            [
            "user_id" => 1,
            "name" => "Fire in Bauleni",
            "type" => "Fire",
            "area" => "Bauleni",
            "details" => "A fire was reported in Bauleni. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.434996,
            "lng" => 28.277593,
            ],
            [
            "user_id" => 1,
            "name" => "Vandalism in Chilenje",
            "type" => "Vandalism",
            "area" => "Chilenje",
            "details" => "A vandalism was reported in Chilenje. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.383339,
            "lng" => 28.277533,
            ],
            [
            "user_id" => 1,
            "name" => "Flood in Mtendere",
            "type" => "Flood",
            "area" => "Mtendere",
            "details" => "A flood was reported in Mtendere. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.437845,
            "lng" => 28.236101,
            ],
            [
            "user_id" => 1,
            "name" => "Vandalism in Mtendere",
            "type" => "Vandalism",
            "area" => "Mtendere",
            "details" => "A vandalism was reported in Mtendere. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.433796,
            "lng" => 28.319044,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Chawama",
            "type" => "Disease Outbreak",
            "area" => "Chawama",
            "details" => "A disease outbreak was reported in Chawama. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.439592,
            "lng" => 28.275049,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Ngombe",
            "type" => "Disease Outbreak",
            "area" => "Ngombe",
            "details" => "A disease outbreak was reported in Ngombe. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.465514,
            "lng" => 28.299051,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Matero",
            "type" => "Disease Outbreak",
            "area" => "Matero",
            "details" => "A disease outbreak was reported in Matero. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.436475,
            "lng" => 28.305103,
            ],
            [
            "user_id" => 1,
            "name" => "Vandalism in Kabwata",
            "type" => "Vandalism",
            "area" => "Kabwata",
            "details" => "A vandalism was reported in Kabwata. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.388224,
            "lng" => 28.250192,
            ],
            [
            "user_id" => 1,
            "name" => "Fire in Matero",
            "type" => "Fire",
            "area" => "Matero",
            "details" => "A fire was reported in Matero. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.439795,
            "lng" => 28.280431,
            ],
            [
            "user_id" => 1,
            "name" => "Accident in Kanyama",
            "type" => "Accident",
            "area" => "Kanyama",
            "details" => "A accident was reported in Kanyama. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.367861,
            "lng" => 28.313095,
            ],
            [
            "user_id" => 1,
            "name" => "Theft in Bauleni",
            "type" => "Theft",
            "area" => "Bauleni",
            "details" => "A theft was reported in Bauleni. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.367213,
            "lng" => 28.310693,
            ],
            [
            "user_id" => 1,
            "name" => "Flood in Garden",
            "type" => "Flood",
            "area" => "Garden",
            "details" => "A flood was reported in Garden. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.417076,
            "lng" => 28.290101,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Mtendere",
            "type" => "Disease Outbreak",
            "area" => "Mtendere",
            "details" => "A disease outbreak was reported in Mtendere. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.404737,
            "lng" => 28.325333,
            ],
            [
            "user_id" => 1,
            "name" => "Flood in Ngombe",
            "type" => "Flood",
            "area" => "Ngombe",
            "details" => "A flood was reported in Ngombe. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.371928,
            "lng" => 28.315145,
            ],
            [
            "user_id" => 1,
            "name" => "Disease Outbreak in Kanyama",
            "type" => "Disease Outbreak",
            "area" => "Kanyama",
            "details" => "A disease outbreak was reported in Kanyama. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.367462,
            "lng" => 28.309,
            ],
            [
            "user_id" => 1,
            "name" => "Fire in Ngombe",
            "type" => "Fire",
            "area" => "Ngombe",
            "details" => "A fire was reported in Ngombe. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.450375,
            "lng" => 28.25448,
            ],
            [
            "user_id" => 1,
            "name" => "Accident in Chilenje",
            "type" => "Accident",
            "area" => "Chilenje",
            "details" => "A accident was reported in Chilenje. Further investigation is ongoing.",
            "status" => "resolved",
            "lat" => -15.408086,
            "lng" => 28.240657,
            ],
            [
            "user_id" => 1,
            "name" => "Flood in Garden",
            "type" => "Flood",
            "area" => "Garden",
            "details" => "A flood was reported in Garden. Further investigation is ongoing.",
            "status" => "reported",
            "lat" => -15.441112,
            "lng" => 28.308243,
            ],
        ]);
    }
}
